### PR TITLE
add eslint-config-sane rules

### PR DESCRIPTION
**Pull request by kellyselden**

### CODE REVIEW

**Comment by Turbo87** [comment]
I can recommend https://github.com/simplabs/eslint-config-simplabs ;)

**Comment by kellyselden** [comment]
@Turbo87 I'll try that out.

**Comment by kellyselden** [comment]
@Turbo87 That comma dangle though... Don't know if I'm ready for that commitment lol.

**Comment by Turbo87** [comment]
...

**Pull request merged**
