### PR TITLE
allow arrays into the arithmetic macros

### LINKED ISSUE #341: sum doesn't accept an array
It would be nice if `sum` accepted an array:

```javascript
array: Ember.A([{ test: 1 }, { test: 2 }]),
key: 'test',
value: sum(array.mapBy('array', 'key')) // expected: 3
```

But this does not work because `sum` expects stringy property keys, not an array.

### PR DESCRIPTION
**Pull request by kellyselden**
Closes #341.

cc @mwpastore

### CODE REVIEW

**Comment by kellyselden** [comment]
What should the return value be if the array is empty?

**Comment by Fed03** [comment]
erroring?

**Comment by mwpastore** [comment]
That's an interesting question. I think you could probably get away with returning zero,

**Comment by kellyselden** [comment]
> What happens if the array contains something that's not a number?

@Fed03 It would try to add it 😛

**Comment by Fed03** [comment]
> @Fed03 It would try to add it 😛

In that case, I think that NaN would be the right thing to return when array is empty, like suggested by @mwpastore

**Comment by kellyselden** [comment]
I ended up saying empty array is zero. I thought it would be easier to reason this:

`total: sum('array')`

vs

`total: or(sum('total'), 0)` or `total: conditional('total.length', sum('total'), 0)`

**Comment by kellyselden** [comment]
Released in https://github.com/kellyselden/ember-awesome-macros/releases/tag/v0.37.0

**Pull request merged**
