### PR TITLE
ArrayProxy fix

### PR DESCRIPTION
**Pull request by kellyselden**
@marcoow Does this look like the right direction?

### CODE REVIEW

**Comment by Turbo87** [comment]
FWIW, the answer is unfortunately no. or at least in not all cases. I'm still investigating but:
```
arrayVal instanceof Ember.ArrayProxy
-> false
arrayVal.constructor.name
-> "Class"
arrayVal.constructor
-> ƒ DS.ManyArray
```

**Comment by Turbo87** [comment]
it seems that Ember Data is only using an ArrayProxy for async relationships, but not for `async: false` 🤔

**Comment by Turbo87** [comment]
`Ember.isArray(arrayVal)` -> `true`

maybe we should use that instead of `Array.isArray()`?

**Comment by Turbo87** [comment]
looks like I've found this issue before already: https://github.com/kellyselden/ember-awesome-macros/issues/441 😂

**Comment by lolmaus** [comment]
I had attempted to fix this in #424. My PR was ignored and eventually went out of sync.

**Pull request merged**
