### PR TITLE
Use new module imports

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/ember-cli/ember-rfc176-data

### CODE REVIEW

**Comment by kellyselden** [comment]
I reran CI to account for ember-cli-babel v6.5.1, and now it is failing.

**Comment by Turbo87** [comment]
@rwjblue ☝️

**Comment by kellyselden** [comment]
@Turbo87 OK. Hopefully soon, I don't want you to have to deal with many rebases and conflicts.

**Comment by Turbo87** [comment]
@kellyselden just updated this to use `ember-cli-babel@6.6.0` including the new imports :)

**Comment by kellyselden** [comment]
Looks beautiful!

**Pull request merged**
