### PR TITLE
[BUGFIX] Pass all keys to normalizeArrayKey

### PR DESCRIPTION
**Pull request by offirgolan**
Fixes `array.sort` dependent keys

### CODE REVIEW

**Comment by kellyselden** [comment]
Can you supply a failing test for the bug you found in sort?

**Comment by offirgolan** [comment]
@kellyselden I don't have much time this week but I wrote up a quick test in a twiddle to demonstrate the problem.

[Ember Twiddle Failing Test Case](https://ember-twiddle.com/687a7182a510c272b6b126695a23c858?openFiles=tests.unit.controllers.awesome-array-sort-test.js%2C)

**Comment by offirgolan** [comment]
🔔 @kellyselden

**Comment by kellyselden** [comment]
Unfortunately, this is not the correct fix. The sort macro needs a bit of work. It needs to use `createClassComputed` like here: https://github.com/kellyselden/ember-awesome-macros/blob/master/addon/array/find-by.js

First `createClassComputed` resolves the `sortDefinition` keys for you, then you needs to split it up like here https://github.com/kellyselden/ember-awesome-macros/blob/master/addon/array/sort.js#L24-L35. Finally, you can do the `normalizeArrayKey` stuff into a new `computed` just like this line: https://github.com/kellyselden/ember-awesome-macros/blob/master/addon/array/find-by.js#L8. Then it should be watching all your sort keys.

Let me know if this makes sense.

**Pull request closed without merging**
